name: Publish Docker image

on:
  push:
    branches:
      - '**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract CUDA version from Dockerfile
        id: extract_cuda_version
        run: |
          CUDA_VERSION=$(grep -oP '(?<=FROM shiertier/cuda:)[0-9]+\.[0-9]+' Dockerfile)
          echo "::set-output name=cudavision::$CUDA_VERSION"

      - name: Extract Miniconda version from Dockerfile
        id: extract_miniconda_version
        run: |
          MINICONDA_VERSION=$(grep -oP '(?<=RUN cd /root && wget https://repo.anaconda.com/miniconda/Miniconda3-)[^_]+' Dockerfile)
          echo "::set-output name=tag::$MINICONDA_VERSION"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: shiertier/cuda-py:cu${{ steps.extract_cuda_version.outputs.cudavision }}-${{ steps.extract_miniconda_version.outputs.tag }}
