name: Publish Docker image

on:
  push:
    tags: cuda**

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in workspace
        run: ls -la

      - name: Print current directory
        run: pwd
        
      - name: Extract tag from Dockerfile
        id: extract_tag
        run: |
          git clone https://github.com/shiertier/dockers
          cd ./dockers
          TAG=$(head -n 1 Dockerfile | sed 's/^# //')
          echo "::set-output name=tag::$TAG"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: shiertier/${{ steps.extract_tag.outputs.tag }}

