name: Docker Squash and Push

on:
  push:
    branches:
      - '**'

jobs:
  squash_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Clean up /opt directory
        run: |
          cd /opt
          find . -maxdepth 1 -mindepth 1 '!' -path ./containerd '!' -path ./actionarchivecache '!' -path ./runner '!' -path ./runner-cache -exec rm -rf '{}' ';'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install docker-squash
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install docker-squash

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Squash Docker image
        run: |
          docker pull nvcr.io/nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04
          docker-squash -f 70 -t cuda:12.6 nvcr.io/nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04
          echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login registry.cn-hangzhou.aliyuncs.com --username=hollybody --password-stdin
          docker tag cuda:12.6 registry.cn-hangzhou.aliyuncs.com/shiertier/cuda:12.6.2
          docker push registry.cn-hangzhou.aliyuncs.com/shiertier/cuda:12.6.2
